// Action types
export const GET_ABSENTEES_SUCCESS = 'GET_ABSENTEES_SUCCESS';
export const GET_ABSENTEES_FAILURE = 'GET_ABSENTEES_FAILURE';
export const EXPORT_ABSENTEES_SUCCESS = 'EXPORT_ABSENTEES_SUCCESS';
export const EXPORT_ABSENTEES_FAILURE = 'EXPORT_ABSENTEES_FAILURE';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const UPDATE_PROFILE_PURGE = 'UPDATE_PROFILE_PURGE';

export const GET_CUSTOMERID_SUCCESS = 'GET_CUSTOMERID_SUCCESS';
export const GET_CUSTOMERID_FAILURE = 'GET_CUSTOMERID_FAILURE';

export const SET_CUSTOMERID_SUCCESS = 'SET_CUSTOMERID_SUCCESS';
export const SET_CUSTOMERID_FAILURE = 'SET_CUSTOMERID_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
